apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: product
  type: ClusterIP
