apiVersion: v1
kind: ConfigMap
metadata:
  name: admin
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            all-namespaces: true
            service-labels:
              spring-boot: "true"
