spring:
  application:
    name: gateway
  gateway:
    discovery:
      locator:
        enabled: true
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

route-definition:
  filter:
    names: "user|product"

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: product
        url: /v3/api-docs/product
